{
    "title": "7 bedroom flat",
    "pageTitle": "7-bedroom-flat",
    "description": "saljlajfkldksjhfjd",
    "category": "residential",
    "propertyType": "apartment",
    "listingType": "sale",
    "view": "sea",
    "price": 12344,
    "priceSymbol": "USD",
    "bedrooms": 4,
    "bathrooms": 3,
    "halfBathrooms": 1,
    "squareFootage": 1234,
    "squareSymbol": "sqft",
    "yearBuilt": 1997,
    "lotArea": 1234.34,
    "lotAreaSymbol": "sqft",
    "image": "https://www.thehouse48.com/wp-content/uploads/WPL/54378/img_DSC_0015-1280x700.jpg",
    "street": "VLORE, ALBANIA",
    "city": "VLORE",
    "webSiteURL": "https://www.luxuryestate.com/p128037603-chalet-for-sale-montevideo",
  "webSiteName": "Luxury estate"
}